OMNeT++ Simulation Library: cDensityEstBase Class Reference
cDensityEstBase Class Reference abstract
Statistical Result Collection
#include <cdensityestbase.h>
Description
Abstract base class for density estimation classes.
For the histogram classes, you need to specify the number of cells and the range. Range can either be set explicitly or you can choose automatic range determination.
Automatic range estimation works in the following way:
The first numPrecollect observations are stored.
After having collected a given number of observations, the actual histogram is set up. The range (min, max) of the initial values is expanded rangeExtensionFactoror times, and the result will become the histogram's range (rangeMin, rangeMax). Based on the range, the cells are layed out.
Then the initial values that have been stored up to this point will be transferred into the new histogram structure and their store is deleted – this is done by the transform() function.
You may also explicitly specify the lower or upper limit and have the other end of the range estimated automatically. The setRange...() member functions of cDensityEstBase deal with setting up the histogram range. It also provides pure virtual functions transform() etc.
Subsequent observations are placed in the histogram structure. If an observation falls out of the histogram range, the underflow or overflow counter is incremented.
Classes
struct Cell
Information about a cell. This struct is not used internally by histogram and histogram-like classes, only to return information to the user.
Public Types
Public Member Functions
Constructors, destructor, assignment.
cDensityEstBase (const cDensityEstBase &other)
cDensityEstBase (const char *name=nullptr, bool weighted=false)
virtual ~cDensityEstBase ()
cDensityEstBase & operator= (const cDensityEstBase &res)
Redefined cObject member functions.
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
Redefined cStatistic member functions.
virtual void collect (double value) override
virtual void collect2 (double value, double weight) override
virtual void merge (const cStatistic *other) override
virtual void clearResult () override
virtual void saveToFile (FILE *) const override
virtual void loadFromFile (FILE *) override
Selecting the method of setting up the histogram range.
virtual void setRange (double lower, double upper)
virtual void setRangeAuto (int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setRangeAutoLower (double upper, int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setRangeAutoUpper (double lower, int numPrecollect=100, double rangeExtensionFactor=2.0)
virtual void setNumPrecollectedValues (int numPrecollect)
virtual int getNumPrecollectedValues () const
virtual double getRangeExtensionFactor () const
Transformation.
virtual bool isTransformed () const
virtual void transform ()=0
Accessing histogram cells.
virtual int getNumCells () const =0
virtual double getBasepoint (int k) const =0
virtual double getCellValue (int k) const =0
virtual double getCellPDF (int k) const
virtual int64_t getUnderflowCell () const
virtual int64_t getOverflowCell () const
virtual double getUnderflowSumWeights () const
virtual double getOverflowSumWeights () const
virtual Cell getCellInfo (int k) const
Density and cumulated density approximation functions.
virtual double getPDF (double x) const =0
virtual double getCDF (double x) const =0
Public Member Functions inherited from cStdDev
cStdDev (const cStdDev &r)
cStdDev (const char *name=nullptr, bool weighted=false)
virtual ~cStdDev ()
cStdDev & operator= (const cStdDev &res)
virtual cStdDev * dup () const override
virtual std::string str () const override
virtual bool isWeighted () const override
virtual long getCount () const override
virtual double getSum () const override
virtual double getSqrSum () const override
virtual double getMin () const override
virtual double getMax () const override
virtual double getMean () const override
virtual double getStddev () const override
virtual double getVariance () const override
virtual double getWeights () const override
virtual double getWeightedSum () const override
virtual double getSqrSumWeights () const override
virtual double getWeightedSqrSum () const override
virtual double draw () const override
Public Member Functions inherited from cStatistic
cStatistic (const cStatistic &r)
cStatistic (const char *name=nullptr)
virtual ~cStatistic ()
cStatistic & operator= (const cStatistic &res)
virtual void collect (SimTime value)
virtual void collect2 (SimTime value, double weight)
virtual void collect2 (double value, SimTime weight)
virtual void collect2 (SimTime value, SimTime weight)
virtual void setTransientDetectionObject (cTransientDetection *object)
virtual void setAccuracyDetectionObject (cAccuracyDetection *object)
virtual cTransientDetection * getTransientDetectionObject () const
virtual cAccuracyDetection * getAccuracyDetectionObject () const
_OPPDEPRECATED double random () const
virtual void record ()
virtual void recordWithUnit (const char *unit)
virtual void recordAs (const char *name, const char *unit=nullptr)
Public Member Functions inherited from cRandom
cRandom (cRNG *rng)
cRandom (const char *name=nullptr, cRNG *rng=nullptr)
virtual ~cRandom ()
virtual void setRNG (cRNG *rng)
cRNG * getRNG () const
Public Member Functions inherited from cOwnedObject
cOwnedObject ()
cOwnedObject (const char *name, bool namepooling=true)
cOwnedObject (const cOwnedObject &obj)
virtual ~cOwnedObject ()
cOwnedObject & operator= (const cOwnedObject &o)
virtual cObject * getOwner () const override
virtual bool isOwnedObject () const override
virtual bool isSoftOwner () const
Public Member Functions inherited from cNamedObject
cNamedObject ()
cNamedObject (const char *name, bool namepooling=true)
cNamedObject (const cNamedObject &obj)
virtual ~cNamedObject ()
cNamedObject & operator= (const cNamedObject &o)
virtual void setName (const char *s)
virtual const char * getName () const override
virtual void setNamePooling (bool b)
virtual bool getNamePooling ()
Public Member Functions inherited from cObject
cObject ()
cObject (const cObject &other)
virtual ~cObject ()
virtual const char * getClassName () const
bool isName (const char *s) const
virtual const char * getFullName () const
virtual std::string getFullPath () const
const cObject * getThisPtr () const
virtual _OPPDEPRECATED std::string info () const
virtual _OPPDEPRECATED std::string detailedInfo () const
virtual void forEachChild (cVisitor *v)
cObject * findObject (const char *name, bool deep=true)
void copyNotSupported () const
Protected Member Functions
virtual void setupRange ()
virtual void collectTransformed (double value)=0
virtual void collectTransformed2 (double value, double weight)=0
Protected Member Functions inherited from cObject
virtual void take (cOwnedObject *obj)
virtual void drop (cOwnedObject *obj)
void dropAndDelete (cOwnedObject *obj)
Additional Inherited Members
Static Public Member Functions inherited from cOwnedObject
static long getTotalObjectCount ()
static long getLiveObjectCount ()
static void resetObjectCounters ()
static cDefaultList * getDefaultOwner ()
Member Enumeration Documentation
enum RangeMode
Constants for histogram range_mode.
Constructor & Destructor Documentation
cDensityEstBase (const cDensityEstBase & other) inline
Copy constructor.
References cStatistic::collect(), and cStatistic::collect2().
cDensityEstBase (const char * name = nullptr, bool weighted = false) explicit
Constructor.
virtual ~cDensityEstBase () virtual
Destructor.
Member Function Documentation
cDensityEstBase& operator= (const cDensityEstBase & res)
Assignment operator. The name member is not copied; see cNamedObject's operator=() for more details.
virtual void parsimPack (cCommBuffer * buffer) const override virtual
Serializes the object into an MPI send buffer. Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStdDev.
Reimplemented in cHistogram, cKSplit, cVarHistogram, cPSquare, and cHistogramBase.
virtual void parsimUnpack (cCommBuffer * buffer) override virtual
Deserializes the object from an MPI receive buffer Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cStdDev.
Reimplemented in cHistogram, cKSplit, cVarHistogram, cPSquare, and cHistogramBase.
virtual void collect (double value) override virtual
Collects one value. Before the histogram was transformed, this method simply adds the value to the table of pre-collected values. When the number of pre-collected observations reaches a limit, the transform() method is called. After transformation, it calls collectTransformed() to update the stored statistics with this value.
Reimplemented from cStdDev.
Reimplemented in cLongHistogram.
Referenced by cLongHistogram::collect().
virtual void collect2 (double value, double weight) override virtual
Collects one observation with a given weight. The weight must not be negative. (Zero-weight observations are allowed, but will not affect mean and stddev.)
Reimplemented from cStdDev.
virtual void merge (const cStatistic * other) override virtual
Updates this object with data coming from another statistics object – as if this object had collected observations fed into the other object as well. Throws an error if the other object is not a cDensityEstBase.
Reimplemented from cStdDev.
Reimplemented in cKSplit, and cPSquare.
virtual void clearResult () override virtual
Clears the results collected so far.
Reimplemented from cStdDev.
Reimplemented in cVarHistogram, and cHistogramBase.
virtual void saveToFile (FILE *) const override virtual
Writes the contents of the object into a text file.
Reimplemented from cStdDev.
Reimplemented in cHistogram, cKSplit, cPSquare, cVarHistogram, and cHistogramBase.
virtual void loadFromFile (FILE *) override virtual
Reads the object data from a file, in the format written out by saveToFile().
Reimplemented from cStdDev.
Reimplemented in cHistogram, cKSplit, cPSquare, cVarHistogram, and cHistogramBase.
virtual void setRange (double lower, double upper) virtual
Sets the histogram range explicitly to [lower, upper]. When this method is used, setNumPrecollectedValues() is not needed.
Reimplemented in cPSquare.
virtual void setRangeAuto (int numPrecollect = 100, double rangeExtensionFactor = 2.0) virtual
Selects a histogram range setup method where the range will be determined entirely from a set of pre-collected values.
When called, the histogram range will be determined from the first numPrecollect values, extending their range symmetrically by rangeExtensionFactor. For example, after a call to setRangeAuto(100, 1.3), the histogram will be set up after pre-collecting 100 values, the range being the range of the 100 pre-collected values extended 1.3 times symmetrically.
Reimplemented in cPSquare.
virtual void setRangeAutoLower (double upper, int numPrecollect = 100, double rangeExtensionFactor = 2.0) virtual
Selects a histogram range setup method where the upper bound of the range is fixed and the lower bound is determined from a set of pre-collected values.
The lower bound is calculated by extending the range (minimum of observations, upper) rangeExtensionFactor times.
Reimplemented in cPSquare.
virtual void setRangeAutoUpper (double lower, int numPrecollect = 100, double rangeExtensionFactor = 2.0) virtual
Selects a histogram range setup method where the lower bound of the range is fixed and the upper bound is determined from a set of pre-collected values.
The upper bound is calculated by extending the range (lower, maximum of observations) rangeExtensionFactor times.
Reimplemented in cPSquare.
virtual void setNumPrecollectedValues (int numPrecollect) virtual
Sets the number of values to be pre-collected before transformation takes place. See transform().
Reimplemented in cPSquare.
virtual int getNumPrecollectedValues () const inline virtual
Returns the number of values to be pre-collected before transformation takes place. See transform().
virtual double getRangeExtensionFactor () const inline virtual
Returns the range extension factor, used with histogram range setup. See setRangeAuto() and transform().
virtual void setupRange () protected virtual
Called internally by transform(), this method should determine and set up the histogram range, based on the pre-collected data and the range setup method selected by calls to the setRange(), setRangeAuto(), setRangeAutoLower(), setRangeAutoUpper() methods.
Reimplemented in cHistogram.
virtual void collectTransformed (double value) protected pure virtual
Called internally by collect(), this method collects a value after the histogram has been transformed. Updating the underflow/overflow cells must be handled within this function. This is a pure virtual function; it must be redefined in subclasses.
Implemented in cHistogram, cKSplit, cVarHistogram, and cPSquare.
virtual void collectTransformed2 (double value, double weight) protected pure virtual
Called internally by collect(), this method collects a value after the histogram has been transformed. Updating the underflow/overflow cells must be handled within this function. This is a pure virtual function; it must be redefined in subclasses.
Implemented in cHistogram, cKSplit, cVarHistogram, and cPSquare.
virtual bool isTransformed () const inline virtual
Returns whether the object is transformed. See transform().
virtual void transform () pure virtual
Transforms the table of pre-collected values into an internal histogram structure. This is a pure virtual function. Implementations of transform() are expected to call setupRange(), and set the transformed flag when transformation was successfully done.
Implemented in cKSplit, cVarHistogram, cPSquare, and cHistogramBase.
virtual int getNumCells () const pure virtual
Returns the number of histogram cells used. This method is pure virtual, implementation is provided in subclasses.
Implemented in cKSplit, cPSquare, and cHistogramBase.
virtual double getBasepoint (int k) const pure virtual
Returns the kth histogram cell boundary. Legal values for k are 0 through getNumCells(), that is, there's one more basepoint than the number of cells. getBasepoint(0) returns the lower bound of the first cell, and getBasepoint(getNumCells()) returns the upper bound of the last cell. This method is pure virtual, implementation is provided in subclasses.
Implemented in cHistogram, cKSplit, cVarHistogram, and cPSquare.
virtual double getCellValue (int k) const pure virtual
Returns the number of observations that fell into the kth histogram cell. Before transformation, this method may return zero. See transform(). This method is pure virtual, implementation is provided in subclasses.
Implemented in cHistogram, cKSplit, cVarHistogram, and cPSquare.
virtual double getCellPDF (int k) const virtual
Returns the estimated value of the Probability Density Function within the kth cell. This method simply divides the number of observations in cell k with the cell size and the number of total observations collected. Note that before transformation, getCellValue() and also this method may return zero. See transform().
virtual int64_t getUnderflowCell () const inline virtual
Returns number of observations that were below the histogram range, independent of their weights.
virtual int64_t getOverflowCell () const inline virtual
Returns number of observations that were above the histogram range, independent of their weights.
virtual double getUnderflowSumWeights () const inline virtual
Returns the total weight of the observations that were below the histogram range.
virtual double getOverflowSumWeights () const inline virtual
Returns the total weight of the observations that were above the histogram range.
virtual Cell getCellInfo (int k) const virtual
Combines the functionality of getBasepoint(), getCellValue() and getCellPDF() into a single call.
virtual double getPDF (double x) const pure virtual
Returns the estimated value of the Probability Density Function at a given x. This is a pure virtual function, implementation is provided in subclasses implementing concrete histogram types.
Implemented in cHistogram, cKSplit, cPSquare, and cVarHistogram.
virtual double getCDF (double x) const pure virtual
Returns the estimated value of the Cumulative Density Function at a given x. This is a pure virtual function, implementation is provided in subclasses implementing concrete histogram types.
Implemented in cHistogram, cKSplit, cPSquare, and cVarHistogram.
The documentation for this class was generated from the following file:
cdensityestbase.h